/* eslint-disable @typescript-eslint/no-explicit-any */
// Generated by https://quicktype.io

export interface DiscordBody {
  app_permissions:     string;
  application_id:      string;
  channel:             Channel;
  channel_id:          string;
  data:                Data;
  entitlement_sku_ids: string[];
  entitlements:        string[];
  guild:               Guild;
  guild_id:            string;
  guild_locale:        string;
  id:                  string;
  locale:              string;
  member:              Member;
  token:               string;
  type:                number;
  version:             number;
}

export interface Channel {
  flags:               number;
  guild_id:            string;
  id:                  string;
  last_message_id:     string;
  name:                string;
  nsfw:                boolean;
  parent_id:           string;
  permissions:         string;
  position:            number;
  rate_limit_per_user: number;
  topic:               string;
  type:                number;
}

export interface Data {
  id:   string;
  name: string;
  type: number;
}

export interface Guild {
  features: any[];
  id:       string;
  locale:   string;
}

export interface Member {
  avatar:                       null;
  communication_disabled_until: null;
  deaf:                         boolean;
  flags:                        number;
  joined_at:                    string;
  mute:                         boolean;
  nick:                         null;
  pending:                      boolean;
  permissions:                  string;
  premium_since:                null;
  roles:                        string[];
  unusual_dm_activity_until:    null;
  user:                         User;
}

export interface User {
  avatar:            string;
  avatar_decoration: null;
  discriminator:     string;
  global_name:       string;
  id:                string;
  public_flags:      number;
  username:          string;
}
